version: '3'
services: 
    postgres:
        image: danglingmind/dmblogs-postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=danglingmind
            - POSTGRES_PASSWORD=#ricky2327
            - POSTGRES_DB=blogapp
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
            - 5432:5432
        volumes: 
            - db-data:/var/lib/postres/data
        networks: 
            - overlay

    redis:
        image: redis
        container_name: redis
        ports: 
            - 6379:6379
        networks: 
            - overlay
        restart: always

    backend:
        image: danglingmind/dmblogs-backend
        container_name: dmblogs-backend
        ports:
            - "8000:8000"
        networks: 
            - overlay
        depends_on: 
            - redis 
            - postgres

volumes:
    db-data:
        external: false

networks:
    overlay: