name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Prateek'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Download project dependencies
        run: go mod vendor
        
      - name: Build
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Save application binary for next step
        uses: actions/upload-artifact@v2
        with:
          name: dmblogs
          path: dmblogs

  Integration-Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - name: Download application binary
        uses: actions/download-artifact@v2
        with:
          name: dmblogs

      - name: Change permission for dmblogs
        run: chmod 755 dmblogs

      - name: Setup Integration test environment
        run: make docker.start.components
          
      - name: Run integration tests
        run: |
          docker ps
          docker logs dmblogs-backend
          make test.integration
      
      - name: Teardown Integration test environment
        run: make docker.stop

  Tag:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag }}
    needs: Integration-Test
    steps:
      - uses: actions/checkout@v2

      - name: Preparing to tag master after a push
        id: create_tag
        run: |
          ./generate-tag.sh
          echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

  Push-To-Docker-Registry:
    if: ${{ github.event_name == 'push' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: Tag
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download application binary
        uses: actions/download-artifact@v2
        with:
          name: dmblogs
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: danglingmind/dmblog-go-backend:v${{ needs.Tag.outputs.tag_name }}
