name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:
    - name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        
      - name: Build
        run: make build

      - name: Test
        run: make test

  Test:
    - name: Integration tests
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.15

        - name: Setup Integration test environment
          run: make docker.start.components

        - name: Run integration tests
          run: make test.integration
        
        - name: Teardown Integration test environment
          run: make docker.stop

