name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    - name: Integration tests
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.15

        - name: Run Unit Tests
          run: make test

        - name: Setup Integration test environment
          run: make docker.start.components

        - name: Run integration tests
          run: make test.integration
        
        - name: Teardown Integration test environment
          run: make docker.stop

  Build:
    - name: Build application
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.15
          
        - name: Build
          run: make build

