name: Release - Build Image & Deploy

on:
  push:
    branches:
      - 'release-*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DB_REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/download-artifacts@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
            -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f Dockerfile.backend .
        run: docker build -t $DB_REPO:latest -t $DB_REPO:${GITHUB_SHA::8} -f Dockerfile.postgres .
      - name: Publish Docker images
        run: docker push $REPO
        run: docker push $DB_REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          data: "{ 'myField': 'myFieldValue'}"
