name: Release - Build Image & Deploy

on:
  push:
    branches:
      - 'release-*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DB_REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build Service Docker images
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f Dockerfile.backend .

      - name: Build Postgres Docker images
        run: docker build -t $DB_REPO:latest -t $DB_REPO:${GITHUB_SHA::8} -f Dockerfile.postgres .

      - name: Publish Backend Docker images
        run: docker push $REPO
        
      - name: Publish Postgres Docker images
        run: docker push $DB_REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          data: "{ 'myField': 'myFieldValue'}"
